#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Website Optimisation
title: Optimisation


# Short bio or description (displayed in the header)
description: Website Optimisation

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: /images/Octocat.png
avatar: /images/saltire.png

#
# Flags below are optional
#

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://scotentSD.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/optimisation"

excerpt_separator: "<!--more-->"

#
# !! You don't need to change any of the configuration flags below !!
#
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
# README.md
  - CNAME

theme: jekyll-theme-slate

plugins:
  - jekyll-relative-links
  
  
prose:
  rooturl: ''
  siteurl: 'http://scotentSD.github.io/optimisation/'
  relativeLinks: 'http://scotentSD.github.io/optimisation/links.jsonp'
  media: 'files'
  ignore: [links.jsonp,  _config.yml,  media,  assets,  _sass,  _layouts, _includes, _flist, _drafts, images,_templates ,mktest, data.json, data2.json, data2.jsonp,old, test, png,  timeline.css, links_copy.jsonp, testrounds, js, timelinelight.md, timelinelight2.md, timelinelight3.md,  timeline_summary2.md, timeline_summary.md, timeline.md]
  metadata:
   _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "type"
      field:
        element: "select"
        label: "Type"
        placeholder: ""
        options:
          - name: " lab "
            value: "lab"
          - name: " online "
            value: "online"
          - name: " a11y "
            value: "a11y"
          - name: " other "
            value: "other"
          - name: " partner"
            value: "partner"
    - name: "phase"
      field:
        element: "select"
        label: "Phase"
        placeholder: ""
        options:
         - name: "discovery"
           value: "discovery"
         - name: "alpha"
           value: "alpha"
         - name: "beta"
           value: "beta"
         - name: "live"
           value: "live"
    - name: "initials"
      field:
        element: "text"
        label: "Initials"
        value: ""
    - name: "display_date"
      field:
        element: "text"
        label: "Display_Date"
        value: ""
    - name: "tltitle"
      field:
        element: "text"
        label: "Title"
        value: ""
    - name: "return_url"
      field:
        element: "hidden"
        value: "https://scotentsd.github.io/optimisation/timeline/"
